routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@search')->name('site.document.index');
Route::get('/detail/{id}', 'SiteController@detail')->name('site.document.detail');
Route::get('/search/data', 'SiteController@search_data')->name('site.document.data');
Route::get('/dashboard', 'UserController@index')->name('dashboard');
Route::get('/profile', 'ProfileController@index')->name('profile.index');

Route::group(['as'=>'admin.','prefix' => 'admin', 'middleware'=>['auth','admin']], function () {
    Route::get('member', 'Admin\MemberController@index')->name('member.index');
});

Route::group(['as'=>'member.','prefix' => 'member', 'middleware'=>['auth','member']], function () {
    Route::get('document', 'Member\DocumentController@index')->name('document.index');
    Route::get('document/upload', 'Member\DocumentController@create')->name('document.upload');

    Route::post('document/upload', 'Member\DocumentController@store')->name('document.store');
});

require __DIR__.'/auth.php';

app/Models/Document.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'nim',
        'title',
        'abstract',
        'dosen_pembimbing_1',
        'dosen_pembimbing_2',
        'publish_year',
        'image',
        'attachment',
    ];

    public function user(){
        return $this->hasOne('App\Models\User', 'id', 'user_id');
    }

    public function member(){
        return $this->hasOne('App\Models\Member', 'user_id', 'user_id');
    }

}

app/Models/Member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'nim',
        'firstname',
        'lastname',
        'tahun_angkatan',
        'prodi_id',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'birthdate' => 'datetime',
    ];

    public function user(){
        return $this->hasOne('App\Models\User', 'id', 'user_id');
    }

    public function prodi(){
        return $this->hasOne('App\Models\Prodi', 'id', 'prodi_id');
    }
}

app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \App\Models\Member;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'members' => Member::paginate(10)
        ];

        return view('admin.member.member-index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Member/DocumentController.php
<?php


namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \App\Models\Document;
use Auth;
use DB;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'documents' => Document::paginate(10)
        ];

        return view('member.document.document-index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('member.document.document-upload');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {

        $req->validate([
            'titleskripsi' => 'required',
            'dosen1' => 'required',
            'dosen2' => 'required',
            'thn' => 'required',
            'skripsicover' => 'required',
            'skripsisoftfile' => 'required',
            'abstract' => 'required',
            ]);
    
            $fileModel = new Document;
    
            // if($req->file()) {
                
                $fileModel->user_id = Auth::user()->id;
                $fileModel->nim = $req->nim;
                $fileModel->title = $req->titleskripsi;
                $fileModel->abstract = $req->abstract;
                $fileModel->dosen_pembimbing_1 = $req->dosen1;
                $fileModel->dosen_pembimbing_2 = $req->dosen2;
                $fileModel->publish_year = $req->thn;;
                
                DB::beginTransaction();

                try{
                    $fileName = time().'_'.$req->file('skripsisoftfile')->getClientOriginalName();
                    $req->file('skripsisoftfile')->move(public_path('uploads'), $fileName);
                    $fileModel->attachment = time().'_'.$req->file('skripsisoftfile')->getClientOriginalName();
                    
                    $fileName2 = time().'_'.$req->file('skripsicover')->getClientOriginalName();
                    $req->file('skripsicover')->move(public_path('uploads'), $fileName2);
                    $fileModel->image = time().'_'.$req->file('skripsicover')->getClientOriginalName();
                    
                    $fileModel->save();
                    DB::commit();
                } catch (\Exception $e) {
                    DB::rollback();
                    dd($e);
                }

                return back()
                ->with('success','File has been uploaded.')
                ->with('file', $fileName2);
            // }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/member/document/document-index.blade.php
<x-app-layout>
<div class="card">
						<div class="card-header">
							<h5 class="card-title">List Document</h5>
						</div>

						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th>#</th>
										<th>User</th>
										<th>Nim</th>
										<th>Title</th>
										<th>Abstract</th>
										<th>Dosen 1</th>
										<th>Dosen 2</th>
										<th>Tahun Terbit</th>
										<th>Image</th>
										<th>Attachment</th>
									</tr>
								</thead>
								<tbody>
                                    @foreach($documents as $value)
									<tr>
										<td>1</td>
										<td>{{ $value->member->firstname . " " . $value->member->lastname }}</td>
										<td>{{ $value->member->nim }}</td>
										<td>{{ $value->title }}</td>
										<td>{{ $value->abstract }}</td>
										<td>{{ $value->dosen_pembimbing_1 }}</td>
										<td>{{ $value->dosen_pembimbing_2 }}</td>
										<td>{{ $value->publish_year }}</td>
										<td>{{ $value->image }}</td>
										<td>{{ $value->attachment }}</td>
									</tr>
                                    @endforeach
								</tbody>
							</table>
						</div>

                        @if ($documents->lastPage() > 1)
                        <ul class="pagination pagination-flat align-self-center flex-wrap my-2">
                            <li class="page-item {{ ($documents->currentPage() == 1) ? ' disabled' : '' }}">
                                <a href="{{ $documents->url(1) }}" class="page-link"><i class="icon-arrow-left8"></i></a>
                            </li>
                            @for ($i = 1; $i <= $documents->lastPage(); $i++)
                                <li class="page-item {{ ($documents->currentPage() == $i) ? ' active' : '' }}">
                                    <a href="{{ $documents->url($i) }}" class="page-link">{{ $i }}</a>
                                </li>
                            @endfor
                            <li class="page-item {{ ($documents->currentPage() == $documents->lastPage()) ? ' disabled' : '' }}">
                                <a href="{{ $documents->url($documents->currentPage()+1) }}" class="page-link"><i class="icon-arrow-right8"></i></a>
                            </li>
                        </ul>
                        @endif
					</div>
</x-app-layout>

resources/views/member/document/document-upload.blade.php
<x-app-layout>
<div class="card">
    <div class="card-header">
        <h5 class="card-title">Upload Detail Skripsi</h5>
    </div>

    <div class="card-body">
        <form action="{{ route('member.document.store') }}"  method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label>Title:</label>
                <input type="text" id="titleSkripsi" name="titleskripsi" class="form-control" placeholder="Masukkan Judul Skripsi Anda">
            </div>

            <div class="form-group">
                <label>NIM:</label>
                <input type="text" id="nim" name="nim" class="form-control" placeholder="Masukkan Nim Mahasiswa">
            </div>

            <div class="form-group">
                <label>Dosen 1 :</label>
                <select id="dosen1" class="custom-select" name="dosen1">
                    <option disabled>Pilih Dosen Pembimbing 1</option>
                    <option value="sbj">Bpk. Subarjo</option>
                    <option value="spr">Bpk. Supratman</option>
                    <option value="sdr">Bpk. Sudiro</option>
                </select>
            </div>

            <div class="form-group">
                <label>Dosen 2 :</label>
                <select id="dosen2" class="custom-select" name="dosen2">
                    <option disabled>Pilih Dosen Pembimbing 2</option>
                    <option value="sbj">Bpk. Subarjo</option>
                    <option value="spr">Bpk. Supratman</option>
                    <option value="sdr">Bpk. Sudiro</option>
                </select>
            </div>

            <div class="form-group">
                <label>Tahun Terbit :</label>
                <input type="text" id="thn" name="thn" class="form-control" placeholder="Tahun Terbit / Approval Skripsi">
            </div>

            <div class="form-group">
                <label>Upload Cover Skripsi :</label>
                <label class="custom-file">
                    <input type="file" id="skripsiCover" name="skripsicover" class="custom-file-input">
                    <span class="custom-file-label">Choose file</span>
                </label>
            </div>

            <div class="form-group">
                <label>Upload Softfile Skripsi :</label>
                <label class="custom-file">
                    <input type="file" id="skripsiSoftfile" name="skripsisoftfile" class="custom-file-input">
                    <span class="custom-file-label">Choose file</span>
                </label>
            </div>

            <div class="form-group">
                <label>Abstract :</label>
                <textarea rows="5" cols="5" id="abstract" name="abstract" class="form-control" placeholder="Masukan abstraksi / Deskripsi singkat dari judul skripsi"></textarea>
            </div>

            <div class="text-right">
                <button type="submit" class="btn btn-primary">Submit form <i class="icon-paperplane ml-2"></i></button>
            </div>
        </form>
    </div>
</div>
</x-app-layout>