routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@search')->name('site.document.index');
Route::get('/detail/{id}', 'SiteController@detail')->name('site.document.detail');
Route::get('/search/data', 'SiteController@search_data')->name('site.document.data');
Route::get('/dashboard', 'UserController@index')->name('dashboard');
Route::get('/profile', 'ProfileController@index')->name('profile.index');

Route::group(['as'=>'admin.','prefix' => 'admin', 'middleware'=>['auth','admin']], function () {
    Route::get('member', 'Admin\MemberController@index')->name('member.index');
});

Route::group(['as'=>'member.','prefix' => 'member', 'middleware'=>['auth','member']], function () {
    Route::get('document', 'Member\DocumentController@index')->name('document.index');
    Route::get('document/upload', 'Member\DocumentController@create')->name('document.upload');

    Route::post('document/upload', 'Member\DocumentController@store')->name('document.store');
});

require __DIR__.'/auth.php';

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\Document;

class SiteController extends Controller
{
    public function search(Request $req)
    {
        $data = [
            'documents' => Document::where('title', 'like', '%' . $req->input('q') . '%')->paginate(10)
        ];

        return view('site.document-search')->with($data);
    }

    public function search_data(Request $req)
    {

        $documents = Document::where('title', 'like', '%' . $req->input('q') . '%')->paginate(10);

        if($req->ajax()) {
            return response()->json($documents);
        }

		return view('site.document-search')->with($documents);

    }
    
    public function detail($id)
    {
        $data = [
            'document' => Document::where('id', $id)->first()
        ];

        return view('site.document-detail')->with($data);
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/site/document-detail.blade.php
<x-guest-layout>
    <div class="row">
        <div class="col-12 col-lg-8">
            <div class="card card-body">
                <h3>{{ $document->title }}</h3>
                Submitted on {{ $document->publish_year }}
                <br>
                <br>
                <br>
                <br>
                <br>
                {{ $document->member->prodi->fakultas->name }} | {{ $document->member->prodi->name }}
                <br>
                <br>
                {{ $document->member->nim }}
                <br>
                {{ $document->member->firstname }} {{ $document->member->lastname }}
                <br>
                <br>
                @auth
                <div class="text-left">
                    <a href="{{ URL::to('/uploads') . '/' . $document->attachment }}">
                        <x-button class="btn btn-primary">
                            Lihat selengkapnya
                        </x-button>
                    </a>
                </div>
                @endauth
            </div>
        </div>

        <div class="col-12 col-lg-4">
            <div class="mb-3">
                <a href="#"><img src="{{ URL::to('/uploads') . '/' . $document->image }}" class="img-fluid rounded" alt=""></a>
            </div>
        </div>

        <div class="col-12">
            <h3>ABSTRAKSI</h3>
            <p>{{ $document->abstract }}</p>
        </div>
    </div>

</x-guest-layout>

resources/views/site/document-search.blade.php
<x-guest-layout>
        <!-- Validation Errors -->
        <x-auth-validation-errors class="mb-4" :errors="$errors" />

		 <!-- Search field -->
         <div class="card">
        <div class="card-body">
            <form class="sk-form">
                <div class="d-sm-flex">
                    <div class="form-group-feedback form-group-feedback-left flex-grow-1 mb-3 mb-sm-0">
                        <input type="text" class="form-control form-control-lg sk-search" name="q" placeholder="Search" value="{{ Request::get('q') }}">
                        <div class="form-control-feedback form-control-feedback-lg">
                            <i class="icon-search4 text-muted"></i>
                        </div>
                    </div>

                    <div class="ml-sm-3">
                        <button type="submit" class="btn btn-primary btn-lg w-100 w-sm-auto sk-btn">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- /search field -->


    <!-- Search results -->
    <div class="row">
        <div class="col-12 col-lg-8">
            <div class="card card-body sk-body">

                <ul class="media-list mb-3 sk-contents">
                    @foreach($documents as $document)
                    <li class="media sk-content">
                        <div class="media-body">
                            <h6 class="media-title"><a href="{{ route('site.document.detail', ['id' => $document->id]) }}">{{ $document->title }}</a></h6>
                            {{ $document->abstract }}
                        </div>
                    </li>
                    @endforeach
                </ul>

                @if ($documents->lastPage() > 1)
                <ul class="pagination pagination-flat align-self-center flex-wrap my-2">
                    <li class="page-item {{ ($documents->currentPage() == 1) ? ' disabled' : '' }}">
                        <a href="{{ $documents->url(1) }}" class="page-link"><i class="icon-arrow-left8"></i></a>
                    </li>
                    @for ($i = 1; $i <= $documents->lastPage(); $i++)
                        <li class="page-item {{ ($documents->currentPage() == $i) ? ' active' : '' }}">
                            <a href="{{ $documents->url($i) }}" class="page-link">{{ $i }}</a>
                        </li>
                    @endfor
                    <li class="page-item {{ ($documents->currentPage() == $documents->lastPage()) ? ' disabled' : '' }}">
                        <a href="{{ $documents->url($documents->currentPage()+1) }}" class="page-link"><i class="icon-arrow-right8"></i></a>
                    </li>
                </ul>
                @endif
            </div>
        </div>

        <div class="col-12 col-lg-4">
            <div class="card card-body">
                <div class="mb-3">
                    <a href="#"><img src="{{ URL::to('/') }}/images/placeholder.png" class="img-fluid rounded" alt=""></a>
                </div>

                <h5 class="font-weight-semibold">Sistem Informasi Skripsi</h5>
                <p class="mb-3">Merupakan sistem yang diharapkan dapat membantu Fakultas Ilmu Komputer dan Teknologi Informasi (FKTI) untuk mengatur pengarsipan data-data skripsi yang telah dikerjakan oleh para mahasiswanya menjadi lebih rapi, aman dan mudah untuk dikelola</p>
            </div>
        </div>
    </div>
    <!-- /search results -->

        
</x-guest-layout>