routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'SiteController@search')->name('site.document.index');
Route::get('/detail/{id}', 'SiteController@detail')->name('site.document.detail');
Route::get('/search/data', 'SiteController@search_data')->name('site.document.data');
Route::get('/dashboard', 'UserController@index')->name('dashboard');
Route::get('/profile', 'ProfileController@index')->name('profile.index');

Route::group(['as'=>'admin.','prefix' => 'admin', 'middleware'=>['auth','admin']], function () {
    Route::get('member', 'Admin\MemberController@index')->name('member.index');
});

Route::group(['as'=>'member.','prefix' => 'member', 'middleware'=>['auth','member']], function () {
    Route::get('document', 'Member\DocumentController@index')->name('document.index');
    Route::get('document/upload', 'Member\DocumentController@create')->name('document.upload');

    Route::post('document/upload', 'Member\DocumentController@store')->name('document.store');
});

require __DIR__.'/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
    <html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="csrf-token" content="{{ csrf_token() }}">
            <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Global stylesheets -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
        <link href="{{ asset('css/icons/icomoon/styles.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ asset('css/all.min.css') }}" rel="stylesheet" type="text/css">
        <!-- /global stylesheets -->

        <!-- Core JS files -->
        <script src="{{ asset('js/jquery.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
        <!-- /core JS files -->

        <!-- Theme JS files -->
        <script src="{{ asset('js/app.js') }}"></script>
        <!-- /theme JS files -->

    </head>
    <body>

    @include('layouts.navigation')

	<!-- Page content -->
	<div class="page-content">

        @include('layouts.sidebar')

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Inner content -->
            <div class="content-inner">

                <!-- Page header -->
                <div class="page-header">
                    <div class="page-header-content header-elements-lg-inline">
                        <div class="page-title d-flex">
                            <h4 class="font-weight-semibold">Sistem Informasi Repository Skripsi</h4>
                            <a href="#" class="header-elements-toggle text-body d-lg-none"><i class="icon-more"></i></a>
                        </div>
                        
                        <?php if (Auth::user()->role_id == 2) : ?>
                        <div class="header-elements d-none mb-3 mb-lg-0">
							<div class="d-flex justify-content-center">
								<a href="{{ route('member.document.upload') }}" class="btn btn-link btn-float text-body"><i class="icon-pencil7"></i><span>Upload Document</span></a>
							</div>
						</div>
                        <?php endif; ?>
                    </div>
                </div>
                <!-- /page header -->


                <!-- Content area -->
                <div class="content pt-0">
                    {{ $slot }}
                </div>
                <!-- /content area -->


                <!-- Footer -->
                <div class="navbar navbar-expand-lg navbar-light">
                    <div class="text-center d-lg-none w-100">
                        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
                            <i class="icon-unfold mr-2"></i>
                            Footer
                        </button>
                    </div>

                    <div class="navbar-collapse collapse" id="navbar-footer">
                        <span class="navbar-text">
                            &copy; 2021. Sistem Repository Skripsi
                        </span>
                    </div>
                </div>
                <!-- /footer -->

            </div>
            <!-- /inner content -->

        </div>
        <!-- /main content -->

        </div>
        <!-- /page content -->
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Global stylesheets -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
        <link href="{{ asset('css/icons/icomoon/styles.min.css') }}" rel="stylesheet" type="text/css">
        <link href="{{ asset('css/all.min.css') }}" rel="stylesheet" type="text/css">
        <!-- /global stylesheets -->

        <!-- Core JS files -->
        <script src="{{ asset('js/jquery.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
        <!-- /core JS files -->

        <!-- Theme JS files -->
        <script src="{{ asset('js/app.js') }}"></script>
        <!-- /theme JS files -->
        
</head>

    <body>

        <!-- Main navbar -->
	<div class="navbar navbar-expand-xl navbar-light navbar-static">

		<div class="d-flex flex-1 d-lg-none">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-paragraph-justify3"></i>
			</button>
			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-transmission"></i>
			</button>
		</div>

		<div class="navbar-brand text-center text-lg-left">
			<a href="{{ route('site.document.index') }}" class="d-inline-block">
				<img src="{{ URL::to('/') }}/images/logo_light.png" class="d-none d-sm-block" alt="">
				<img src="{{ URL::to('/') }}/images/logo_icon_light.png" class="d-sm-none" alt="">
			</a>
		</div>
		<div class="d-flex flex-1 pl-3">
			<div class="navbar-brand wmin-0 mr-1">
				<a href="{{ route('site.document.index') }}" class="d-inline-block">
					SIM Repo Skripsi
				</a>
			</div>
		</div>
        <div class="d-flex flex-xl-1 justify-content-xl-end order-0 order-xl-1 pr-3">
			<ul class="navbar-nav navbar-nav-underline flex-row">
                @if (Route::has('login'))
                        @auth
                            <li class="nav-item">
                                <a href="{{ url('/dashboard') }}" class="navbar-nav-link">Dashboard</a>
                            </li>
                        @else
                            <li class="nav-item">
                                <a href="{{ route('login') }}" class="navbar-nav-link">Log in</a>
                            </li>
                            @if (Route::has('register'))
                            <li class="nav-item">
                                <a href="{{ route('register') }}" class="navbar-nav-link">Register</a>
                            </li>
                            @endif
                        @endauth
                @endif

			</ul>
		</div>
	</div>
	<!-- /main navbar -->

	<!-- Page content -->
	<div class="page-content">

        <!-- Main content -->
        <div class="content-wrapper">

            <!-- Inner content -->
            <div class="content-inner">

                <!-- Page header -->
                <div class="page-header">
                    <div class="page-header-content container d-sm-flex">
                        <div class="page-title">
                            <h4 class="font-weight-semibold">Sistem Informasi Repository Skripsi</h4>
                        </div>

                        <div class="my-sm-auto ml-sm-auto mb-3 mb-sm-0">
                        </div>
                    </div>
                </div>
                <!-- /page header -->

                <!-- Content area -->
                <div class="content container pt-0">
                    {{ $slot }}
                </div>
                <!-- /content area -->

                <!-- Footer -->
                <div class="navbar navbar-expand-lg navbar-light">
                    <div class="text-center d-lg-none w-100">
                        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
                            <i class="icon-unfold mr-2"></i>
                            Footer
                        </button>
                    </div>

                    <div class="navbar-collapse collapse" id="navbar-footer">
                        <span class="navbar-text">
                            &copy; 2021. Sistem Repository Skripsi
                        </span>
                    </div>
                </div>
                <!-- /footer -->

            </div>
            <!-- /inner content -->

        </div>
        <!-- /main content -->

    </div>
    <!-- /page content -->

</body>
</html>

resources/views/layouts/navigation.blade.php
<!-- Main navbar -->
<div class="navbar navbar-expand-lg navbar-light navbar-static">
		<div class="d-flex flex-1 d-lg-none">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-paragraph-justify3"></i>
			</button>
			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-transmission"></i>
			</button>
		</div>

		<div class="navbar-brand text-center text-lg-left">
			<a href="index.html" class="d-inline-block">
				<img src="{{ URL::to('/') }}/images/logo_light.png" class="d-none d-sm-block" alt="">
				<img src="{{ URL::to('/') }}/images/logo_icon_light.png" class="d-sm-none" alt="">
			</a>
		</div>

		<div class="collapse navbar-collapse order-2 order-lg-1" id="navbar-mobile">
		</div>

		<ul class="navbar-nav flex-row order-1 order-lg-2 flex-1 flex-lg-0 justify-content-end align-items-center">
			<li class="nav-item nav-item-dropdown-lg dropdown dropdown-user h-100">
				<a href="#" class="navbar-nav-link navbar-nav-link-toggler dropdown-toggle d-inline-flex align-items-center h-100" data-toggle="dropdown">
					<img src="{{ URL::to('/') }}/images/placeholder-person.jpeg" class="rounded-pill" height="34" alt="">
					<span class="d-none d-lg-inline-block ml-2">{{ Auth::user()->name }}</span>
				</a>
				<div class="dropdown-menu dropdown-menu-right">

				<a href="{{ route('profile.index') }}" class="dropdown-item"><i class="icon-user-plus"></i> My profile</a>
                    <div class="dropdown-divider"></div>
					<form method="POST" action="{{ route('logout') }}">
						@csrf
						<a :href="route('logout')"
								onclick="event.preventDefault();
											this.closest('form').submit();" class="dropdown-item"><i class="icon-switch2"></i> Logout</a>
					</form>
				</div>
			</li>
		</ul>
	</div>
	<!-- /main navbar -->

resources/views/layouts/sidebar.blade.php
        <!-- Main sidebar -->
        <div class="sidebar sidebar-light sidebar-main sidebar-expand-lg">

            <!-- Sidebar content -->
            <div class="sidebar-content">

                <!-- User menu -->
                <div class="sidebar-section sidebar-user my-1">
                    <div class="sidebar-section-body">
                        <div class="media">
                            <a href="#" class="mr-3">
                                <img src="{{ URL::to('/') }}/images/placeholder-person.jpeg" class="rounded-circle" alt="">
                            </a>

                            <div class="media-body">
                                <div class="font-weight-semibold">{{ Auth::user()->name }}</div>
                            </div>

                            <div class="ml-3 align-self-center">
                                <button type="button" class="btn btn-outline-light text-body border-transparent btn-icon rounded-pill btn-sm sidebar-control sidebar-main-resize d-none d-lg-inline-flex">
                                    <i class="icon-transmission"></i>
                                </button>

                                <button type="button" class="btn btn-outline-light text-body border-transparent btn-icon rounded-pill btn-sm sidebar-mobile-main-toggle d-lg-none">
                                    <i class="icon-cross2"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /user menu -->


                <!-- Main navigation -->
                <div class="sidebar-section">
                    <ul class="nav nav-sidebar" data-nav-type="accordion">

                        <!-- Main -->
                        <li class="nav-item">
                            <a href="{{ route('dashboard') }}" class="nav-link active">
                                <i class="icon-home4"></i>
                                <span>
                                    Dashboard
                                </span>
                            </a>
                        </li>

                        <?php
                            if (Auth::user()->role_id == 1) {
                                ?>
                                    <li class="nav-item">
                                        <a href="{{ route('admin.member.index') }}" class="nav-link">
                                            <i class="icon-list-unordered"></i>
                                            <span>
                                                List Member
                                            </span>
                                        </a>
                                    </li>
                                <?php
                            } 
                            
                            ?>
                                <li class="nav-item">
                                    <a href="{{ route('member.document.index') }}" class="nav-link">
                                        <i class="icon-list-unordered"></i>
                                        <span>
                                            List Document
                                        </span>
                                    </a>
                                </li>
                            <?php

                            if(Auth::user()->role_id == 2){
                            
                            }
                        ?>
                        <!-- /main -->
                    </ul>
                </div>
                <!-- /main navigation -->

            </div>
            <!-- /sidebar content -->
            
        </div>
        <!-- /main sidebar -->